// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kftwjrlcanttwnsdmgqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdHdqcmxjYW50dHduc2RtZ3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODE2NzAsImV4cCI6MjA3MDA1NzY3MH0.yHDfmHmdadqNqdTfytnrn65iQDoPbKgixFNsYP__t34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});